# Generated by Django 3.1.6 on 2021-05-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Doner',
        ),
    ]
