# Generated by Django 3.1.6 on 2021-05-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0002_auto_20210512_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doner',
            new_name='Donor',
        ),
    ]
