# Generated by Django 3.1.6 on 2021-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0005_auto_20210512_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=50)),
                ('Contact', models.TextField(max_length=10)),
                ('Blood_type', models.TextField(max_length=10)),
            ],
        ),
    ]
