# Generated by Django 3.1.6 on 2021-05-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0008_auto_20210512_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='Recovered_time',
        ),
    ]
